numero1 = 0
numero2 = 0
resultado = 0
operacão = ""

numero1 = int (input ("digite o numero 1:"))
operacao = input ("digite a operacao:")
numero2 =int (input ("digite o numero 2:"))

if operacao =='+':
    resultado = numero1 + numero2
elif operacao == '-':
    resultado == numero1 - numero2
elif operacao == '':
    resultado == numero1 / numero2
elif operacao == '*':
    resultado == numero1 * numero2
else:
    resultado = 'operacao invalida'
print (str (numero1) + '' + str (operacao) + '' + str (numero2) + '=' + str (resultado))
